DROP TABLE DWPROD;
DROP TABLE DWCUST;
DROP TABLE DWSALE;
DROP TABLE A2ERROREVENT;
DROP TABLE GENDERSPELLING;
/
CREATE TABLE A2ERROREVENT(
  ERRORID INTEGER,
  SOURCE_ROWID ROWID,
  SOURCE_TABLE VARCHAR2(30),
  FILTERID INTEGER,
  DATETIME DATE,
  ACTION VARCHAR2(6),
  CONSTRAINT ERROREVENTACTION
  CHECK (ACTION IN ('SKIP','MODIFY'))
);
CREATE TABLE DWPROD(
  DWPRODID NUMBER,
  DWSOURCETABLE VARCHAR2(10),
  DWSOURCEID NUMBER,
  PRODNAME VARCHAR2(50),
  PRODCATNAME VARCHAR2(30),
  PRODMANUNAME VARCHAR2(30),
  PRODSHIPNAME VARCHAR2(30)
);
CREATE TABLE DWCUST(
  DWCUSTID NUMBER,
  DWSOURCEIDBRIS NUMBER,
  DWSOURCEIDMELB NUMBER,
  FIRSTNAME VARCHAR2(20),
  SURNAME VARCHAR2(20),
  GENDER VARCHAR2(1),
  PHONE NUMBER,
  POSTCODE NUMBER,
  CITY VARCHAR2(20),
  STATE VARCHAR2(4),
  CUSTCATNAME VARCHAR2(20)
);
CREATE TABLE DWSALE(
  DWSALEID NUMBER,
  DWCUSTID NUMBER,
  DWPRODID NUMBER,
  DWSOURCEIDBRIS NUMBER,
  DWSOURCEIDMELB NUMBER,
  QTY NUMBER,
  SALE_DWDATEID NUMBER,
  SHIP_DWDATEID NUMBER,
  SALEPRICE NUMBER
);
CREATE TABLE GENDERSPELLING (
  BADDATA VARCHAR2(10),
  GOODDATA VARCHAR(1)
);