version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '5000:5000'

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports: 
      - '80:8080'

